ccflags-y += -Idrivers/media/platform/msm/camera_v2_flamingo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_flamingo/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_flamingo/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
