ccflags-y += -Idrivers/media/platform/msm/camera_v2_flamingo
ccflags-y += -Idrivers/media/platform/msm/camera_v2_flamingo/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_flamingo/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
